<?xml version="1.0" encoding="UTF-8"?><testsuite errors="1" failures="0" name="com.features.search.DataTest" skipped="0" tests="1" time="2.81" timestamp="2016-02-41 05:36:41"><testcase classname="com.features.search.DataTest" name="Test user data"><error message="com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure&#10;&#10;The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server." type="net.thucydides.core.webdriver.WebdriverAssertionError">com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.</error><system-err>com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.&#13;
com.mysql.jdbc.Util.handleNewInstance(Util.java:404)&#13;
com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981)&#13;
com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:339)&#13;
com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)&#13;
com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)&#13;
com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)&#13;
com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:795)&#13;
com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:44)&#13;
com.mysql.jdbc.Util.handleNewInstance(Util.java:404)&#13;
com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)&#13;
com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)&#13;
com.helpers.JDBCHelper.connectToDB(JDBCHelper.java:16)&#13;
com.steps.serenity.DBSteps.connect_to_database(DBSteps.java:19)&#13;
com.features.search.DataTest.test_user_data(DataTest.java:26)&#13;
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
</system-err></testcase></testsuite>